### PR TITLE
fix test

### PR DESCRIPTION
**Pull request by Bobsel**
Fix the failing test and add idea to .gitignore

### CODE REVIEW

**Comment by graphql-java-generator** [comment]
Hum, hum !

Thanks for this PR. 

We're in the process of fixing th integration of another PR, from Gonzalo. 

I asked Gonzalo to finish the work in his PR, including the management of the GraphQLConfiguration.

I merge your PR, and we'll see. But I'm not sure that it will solve the test execution issue, as I get an error that the configuration is not initialized. And I see nothing in your PR that initializes it.

Etienne

**Comment by graphql-java-generator** [comment]
OK, thanks it works.

I ddn't enough in Gonalo's code, as it was just a compilation issue, actually.

Thanks for the PR.
:)

**Comment by gonzalogomezgarcia** [comment]
Hi,
I'm working on a PR to fix the issue. Thanks for the work for solving the compilation issues
Regards

**Comment by gonzalogomezgarcia** [comment]
Hi Bobsel and Etienne,
I've seen that all the changes done by both of you adapt the code to the  1.5.1 version an no extra modifications are required. The integration test compiles and works correctly.
Thanks to both of you!

**Pull request merged**
