### PR TITLE
make schema file folder configurable & fix multiple file handling

### PR DESCRIPTION
**Pull request by Bobsel**
- make the schema file folder configurable by maven plugin configuration
- rename mainResourceesFolder to schemaFileFolder according to schemaFilePattern
- reformat code by eclipse code formater rules

### CODE REVIEW

**Comment by Bobsel** [comment]
Solves #11

**Comment by Bobsel** [comment]
fixes an error in handling multiple schema files, added a test for this

**Comment by graphql-java-generator** [comment]
Hello,

  Thanks for this PR.
NB: You've submitted another PR, which is interesting, and asked by others !
There are some file conflict for merge. I think the good way to integrate it, is to wait that Gonzalo's PR (custom code templates



In the meanwhile, I did a code restructuration, and I integragrated another PR.
We're in the process of integrating another PR, that

**Comment by Bobsel** [comment]
I adjusted the pr and resolved all merge conflicts. the other pr was just to fix the failed test. This pr is based on the other one cause i don't want to create a pr with failing tests. I would be very grateful if the master branch is always stable so I can create pull requests based on the master.

Feel free to merge!

**Comment by graphql-java-generator** [comment]
I plainly agree with you, about failing tests. 

I first merged the Gonzalo's PR in a separated branch to solve this kind of issues. 
I'll keep on doing that, for the next possible failing tests... If I know they are failing: you never know that before merging.

**Comment by Bobsel** [comment]
> I plainly agree with you, about failing tests.
> 
> I first merged the Gonzalo's PR in a separated branch to solve this kind of issues.
> I'll keep on doing that, for the next possible failing tests... If I know they are failing: you never know that before merging.

This can be solved with a build pipeline, right?

**Comment by etienne-sf** [comment]
I've never used this tool. But it seems interesting : it's a bad to never know if tests will be Ok, before I merge a PR.

Yes, I'd be happy if you help me there.
:)

Etienne

**Pull request merged**
