### PR TITLE
Input type custom scalars

### PR DESCRIPTION
**Pull request by paulmchugh777**
Hi Etienne, here is a new PR to add support for custom scalars as fields within input types which are not currently being serialised correctly when the input type is supplied as a single bind parameter.

I've also added the generation of a Field enum in each object POJO to give compile time literals for field names which are useful when composing queries using the builders.

### CODE REVIEW

**Comment by graphql-java-generator** [comment]
Thank you Paul

I was working on the Custom Scalars on a local branch. I'll check that everything works Ok on my side.

Etienne

**Comment by paulmchugh777** [comment]
Hi Etienne,

Thanks for merging my PR. I think there is an issue though, as master is
not building now.

[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile
(default-compile) on project graphql-java-runtime: Compilation failure
[ERROR]
/home/paulmchugh/hack/graphql-maven-plugin-project/graphql-java-runtime/src/main/java/com/graphql_java_generator/client/request/Builder.java:[313,72]
cannot find symbol
[ERROR]   symbol:   method getPackageName()
[ERROR]   location: variable owningClass of type java.lang.Class<?>
[

**Comment by etienne-sf** [comment]
I feared such an issue, with these merges.
Thanks pointing it out.
I'll check that.


I expected that git would avoid such issues, though...
:(

Etienne

**Comment by etienne-sf** [comment]
I just did a full build (mvn clean install). Eveything was Ok.

Did you pull the last version from git ?

**Comment by paulmchugh777** [comment]
Hi Etienne,

Yes. It's a JDK8 compile failure. I've raised an issue #20 and just
submitted a PR for it.

Class.getPackageName() came in at JDK9. My PR should work on both. We're
still on JDK8 at the moment.

Everything else seems to have merged fine and is working for my tests.

Thanks

Paul

**Pull request merged**
