### PR TITLE
feature/custom-tempaltes - enhancements on samples projects build

### PR DESCRIPTION
**Pull request by gonzalogomezgarcia**
**graphql-maven-plugin-samples-CustomTemplates-client** has been modified to launch and use **graphql-maven-plugin-samples-Forum-server** as the server to invoke in te Integration Tests

### CODE REVIEW

**Comment by etienne-sf** [comment]
Thanks Gonzalo
:)

**Comment by etienne-sf** [comment]
Gonzalo, 

The plugin parameter's name is confusing: copyGraphQLJavaSources, when the subject is to copy the runtime code, and has no link with the sources generated from the GraphQL schema.

I renamed it as copyRuntimeSources.

It will be in the next release.

**Comment by gonzalogomezgarcia** [comment]
Hi Etienne,
Sounds better to me!
Have you pushed the changes on the master branch?
Regards

**Comment by etienne-sf** [comment]
Yes it's pushed on the master branch.

I did another change. But it probably has no impact on real code.
As it was a pain to synchronize the custom templates with the real ones, in the plugin-logic module, I removed the "custom" in their file name.

So, to synchronize templates, I do this:
- Copy the files from src/main/resources/templates in this folder
- Do a "Change All" on "/** Generated by the default template from graphql-java-generator */", to be changed by "/** This template is custom **/"

There is a readme in the /src/test/resources/templates_personalization folder

Etienne

**Comment by gonzalogomezgarcia** [comment]
Hi Etienne,
Yes, it's easier to handle the changes that way. 
To even make it easier, I will try this week to implement a way to automatically do this copy and replace action on the test execution so no manual action is required when the original templates change

Regards

**Pull request merged**
