### PR TITLE
Feature/custom code templates

### PR DESCRIPTION
**Pull request by gonzalogomezgarcia**
This PR objective is to provide support to customize the code templates to use in code generation. 

To achieve this feature the follwing changes has been added:

* Modified **GraphqlMavenPlugin** POJO with new param **templates** to configure which templates to overwrite. The key is the alias of the template and the value is the classpath resource related to the file. **PluginCofiguration** and **PluginConfigurationTestHelper** has been modified to add support to the new new property
* **CodeGenerator** has been modified to check if a template has been overwritten. For every invocation to generateTargetFiles, the template to use is resolved with an invocation to the new method **resolveTemplate**. To make easier the management of the available templates, all static properties with the classpath resources for the templates has been refactored to a new enumeration: **CodeTemplate**. Also, each enumeration entry is classified with it scope: client, server or common (applies to both). The available scopes have also been defined in a new enumeration: **CodeTemplateScope**
    
Unit and Integration tests changes:
* Added unit test for **CodeGenerator.resolveTemplate**
* Added integration tests to validate both custom generation of server an client code: **CustomTemplatesClientTest** and **CustomTemplatesServerTest**. Both tests extends **AbstractCustomTemplateIntegrationTest** wich defines assertions for customized code generation. Spring configuration has been added for each test: **CustomTemplates_Client_SpringConfiguration** and **CustomTemplates_Server_SpringConfiguration**. Both configuration extend **AbstractCustomTemplatesSpringConfiguration** which configures code generation with customized templates
* Customized code templates has been added to **graphql-maven-plugin-logic/src/test/resources/tempaltes_personalization**. Every templates generates the first line of the file as "/** This template is custom **/"

Added sample project to show plugin configuration to use customized templates:
* **graphql-maven-plugin-samples-CustomTemplates-resttemplate** defines a customized template for a Query implementation based on a Srping-based QueryExecutor using RestTemplate
* **graphql-maven-plugin-samples-CustomTemplates-client** is a client project showing plugin configuration to use customized template

Documentation update:
* Update Maven site with new page **ustomtemplates.apt.vm** showing usage of new param "templates"
* Updated **README.md** with info related on how to customize code generation on Maven Plugin

### CODE REVIEW

**Comment by graphql-java-generator** [comment]
That's a great change!

This is something I wanted to implement in the future!
:)

So, thank you for that.


BTW, I have issues with this PR. I did a big change in the project, but on client side. And it seems that there are some side-effects on your dev.

I had merge conflict on the CodeGenerator class. I think I solved them properly, as all my part of the code is still Ok. But it seems to have broken your PR.
I slightly updated the test templates, to be compatible with the evolutions I did.

The tests you added don't work.

I have a very strange error with the CustomTemplatesClientTest, link with the file separator.
I'm on Windows. Are you on Linux or Mac ?


To test all that I pushed a branch named 'custom-code-templates'. Can you work from that branch ?

Etienne


(and perhap you can rename your test folder from 'tempaltes_personalization' to 'templates_personalization' ?)

**Comment by graphql-java-generator** [comment]
OK, I did this changes:

- Renamed test folder from 'tempaltes_personalization' to 'templates_personalization' 
- Changed plugin mode of the test CustomTemplates_Server_SpringConfiguration to server

Now, I run into the error for both CustomTemplatesClientTest and CustomTemplatesServerTest. It looks like a JVM bug.
Do you encounter it ?

java.lang.IllegalArgumentException: character to be escaped is missing
	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1020)
	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:998)
	at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1182)
	at java.base/java.lang.String.replaceAll(String.java:2148)
	at com.graphql_java_generator.plugin.compilation_tests.CustomTemplatesServerTest.testGenerateCode(CustomTemplatesServerTest.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by gonzalogomezgarcia** [comment]
Hi Etienne,
I've just merge your changes from your branch "custom-code-template" into my repository branch custom-code-template and solved all conflicts. Thanks for renaming the test templates dir.

It don't get the java.lang.IllegalArgumentException in the CustomTemplatesClientTest and CustomTemplatesServerTest. It seems that is related to the usage of a regular expression to resolve the folder where for the genated code package

On witch operation system are you compiling the project? Windows or Linux? 
Also, witch JDK versión are you using for the compilation?

**Comment by gonzalogomezgarcia** [comment]
I've just realized where the problem is. The problem is in this expression:

`
File generatedSourcesDir = new File(this.pluginConfiguration.getTargetSourceFolder(),
  pluginConfiguration.getPackageName().replaceAll("\\.", File.separator));
`

I guess the problems is that you are compiling in Windows and this scenario arrises: https://stackoverflow.com/questions/13714722/replaceall-with-file-separator

I'm pushing and change on these tests the unsure they work both on Linux and Windows

Regards

**Comment by graphql-java-generator** [comment]
Ok, I merge the Pull Request. 
And we'll see if everything still builds...
:)

**Comment by gonzalogomezgarcia** [comment]
Thanks Etienne,
Please let me know if it builds correctly or not
One question, when are you planning to publish the next release?
Regards!

**Comment by graphql-java-generator** [comment]
The build was KO. I corrected must of the issues.
The biggest was that you were not in the same version. So you didn't see several impacts of the code restructuration I just did.

There is still an issue, that I let you solve : you changed the query/mutation/subsciption constructor, to have only one without arguments.
But the new structure needed a (new) GraphQLConfiguration.

I let you solve this one.


About the next release:

I planned the next version when I can integrate Fragment. I did all this code restructuration to allow this integration. It should be ready in one or two weeks.
If it's too long for you, I can do an intermediate release. And add Fragment later. It's easy for me, as I work on a local branch.

But I'd prefer to wait for the Fragment evolution.

Etienne

**Comment by graphql-java-generator** [comment]
Ok, I got another PR from Bobsel, which solves the last issue.

The integration of this PR is now Ok

**Comment by etienne-sf** [comment]
Gonzalo,

 Can you change the server that is started in the _graphql-maven-plugin-samples-CustomTemplates-resttemplate sample_ from starwars to forum ?

This would speed up the build, as the cargo plugin is really slow to start and stop...

**Comment by gonzalogomezgarcia** [comment]
Ok. 
I'll change it by the end of monday
Regards!

**Comment by gonzalogomezgarcia** [comment]
Just created the PR https://github.com/graphql-java-generator/graphql-maven-plugin-project/pull/37  to use Forum Server on customtemplates-client samples

**Pull request merged**
