### PR TITLE
Make configurable to copy Graphql java runtime classes on code genreation

### PR DESCRIPTION
**Pull request by gonzalogomezgarcia**
Is some cases for cliente code generated may be useful not to copy graphql-java-runtime sources and instead use the library as a dependency. And it will be nice to do it in the Maven plugin configuration

The following changes have been added:
- Modified **GraphqlMavenPlugin** with new configuration property **"copyGrahQLJavaSources"** for enabling copy of graphql java runtime sources when generating sources. The property by default is **"true"** so if not configured the code generation behaves as how it is today. **PluginConfiguration** interface and **PluginConfigurationImpl** has been adapted to hold this new configuration parameter
- Added tests to **CodeGeneratorTest** with two new test cases for testing copy and not copy configuration. To facilitate test execution on IDE, some features have been added to build a mock graphql-java-runtime-sources.jar to test generateCode method invocation. **PluginConfigurationTestHelper** has been modified to hold new copyGraphQLJavaSources parameter and MavenTestHelper has been completed with helper methods to resolve directories for copied sources

### CODE REVIEW

**Comment by graphql-java-generator** [comment]
Hello Gonzalo 

(hum, I guess Gonzalo is your forname, right ?  :) )

I guess I'll merge this PR. 

But before, can you help me on these points:
1) In which case do you think it's useful to do it ?
I of course think around that. And I preferred to have the runtime code in the generated code, to make it easier to use. What's the value of adding a dependency in the client or server code ?

2) Can you provide a doc page to explain to a plugin user how and when to use this PR ?
The easiest way for me is that you update the project site (see the src/site of the root "graphql-maven-plugin-project" project). To do so you'll have to update the site.xml site to create a new entry in the menu, then the web page (Markdown or APT for instance).
But if you give me just a text or a Markdown page, it's Ok. I'll integrate it in the web site.

Etienne

**Comment by gonzalogomezgarcia** [comment]
Hi Etienne,
Yes Gonzalo is my name

The main purpose for adding this feature to the plugin is double:
- Do not generate/keep non-model dependant code if it's already in a dependency. If for some reason an upgrade or patch of the runtime classes is released, the code does not neet to be regenerated and just the graphql-java-runtime dependency version must be updated.
- On the other hand, in some cases, you may want to customize the runtime classes with customized behaviour. I know that this may sound a bit strange but I found myself in this situation.

I've updated the PR whit  the documentation you pointed. I didn't realise that a Maven site was beeing kept in the project. Sorry

Regards

**Comment by graphql-java-generator** [comment]
No, no, don't apologize !
:)

Ok, I'll merge this PR with pleasure.
Then I'll add your above explanation in the site page you added.

Best regards
Etienne

**Comment by graphql-java-generator** [comment]
I pushed an update of the runtime page.

I close this PR.
:)

**Pull request merged**
