### PR TITLE
Pojo builders

### PR DESCRIPTION
**Pull request by paulmchugh777**
Hi Etienne,

Here is a PR to add builders for the generated  POJOs and also a common interface for all the generated POJO field name enumerations that can then be used to simplify the client side Builder() construction.

I've also:
* Fixed another JDK8 compile failure that has crept in and
* Added a wait to fix an intermittently failing test.

Let me know what you think.

Paul

### CODE REVIEW

**Comment by paulmchugh777** [comment]
Hi Etienne,

Regarding the builders, not sure if the __typename field should be included?

Should this be initialised by the builder itself rather than exposed with a with() method?

Paul

**Comment by graphql-java-generator** [comment]
Thanks Paul


The __typename should be requested against the server.

I merge this PR, and we'll check that, if there is an issue there.

Etienne

**Comment by graphql-java-generator** [comment]
Paul,

 I commented the next lines in the test_addFriend() of the StarWars-client, as it generates NullPointerException on my computer.
		// await()
		// .atMost(5, SECONDS)
		// .pollInterval( 1, SECONDS)
		// .until ( () -> characterBefore.getFriends().size() + 1 == characterAfter.getFriends().size() );

Actually, I don't understand this lines. 
What is this 'until' : the value won't change while you wait.

Etienne

**Comment by paulmchugh777** [comment]
Hi Etienne,

Sorry, I made a mistake here. I've updated it on my local copy but the test
still fails intermittently because I think addFriend() sometimes returns
null. Not sure why.

I think my change on this file can be reverted. But there is still an
intermittent problem with addFrield().

I can do a PR for my local change if you want?

I was going to try and have a look at it tonight.

Paul

**Pull request merged**
